### ISSUE TITLE
parameter override expects key to be string

### ISSUE THREAD

**Issue by afletch** [madduck/reclass#72]
@Rtzq0 
If a key is not a string, it will error[1]

Changing https://github.com/madduck/reclass/blob/c08b844b328fa0fe182db49dd423cc203a016ce9/reclass/datatypes/parameters.py#L159 from:
` if key.startswith(ovrprfx) and not initmerge:`
to 
` if str(key).startswith(ovrprfx) and not initmerge:`
.. seems to fix, but I'm unsure of the onward implications of this (my testing shows no problems)

[1]
```Traceback (most recent call last):
  File "/usr/local/bin/reclass-salt", line 9, in <module>
    load_entry_point('reclass==1.4.1', 'console_scripts', 'reclass-salt')()
  File "build/bdist.macosx-10.12-intel/egg/reclass/adapters/salt.py", line 105, in cli
  File "build/bdist.macosx-10.12-intel/egg/reclass/adapters/salt.py", line 38, in ext_pillar
  File "build/bdist.macosx-10.12-intel/egg/reclass/core.py", line 136, in nodeinfo
  File "build/bdist.macosx-10.12-intel/egg/reclass/core.py", line 119, in _nodeinfo
  File "build/bdist.macosx-10.12-intel/egg/reclass/core.py", line 100, in _recurse_entity
  File "build/bdist.macosx-10.12-intel/egg/reclass/core.py", line 94, in _recurse_entity
  File "build/bdist.macosx-10.12-intel/egg/reclass/storage/memcache_proxy.py", line 56, in get_class
  File "build/bdist.macosx-10.12-intel/egg/reclass/storage/memcache_proxy.py", line 39, in _cache_proxy
  File "build/bdist.macosx-10.12-intel/egg/reclass/storage/yaml_fs/__init__.py", line 96, in get_class
  File "build/bdist.macosx-10.12-intel/egg/reclass/storage/yaml_fs/yamlfile.py", line 48, in get_entity
  File "build/bdist.macosx-10.12-intel/egg/reclass/datatypes/parameters.py", line 51, in __init__
  File "build/bdist.macosx-10.12-intel/egg/reclass/datatypes/parameters.py", line 217, in merge
  File "build/bdist.macosx-10.12-intel/egg/reclass/datatypes/parameters.py", line 191, in _merge_recurse
  File "build/bdist.macosx-10.12-intel/egg/reclass/datatypes/parameters.py", line 163, in _merge_dict
  File "build/bdist.macosx-10.12-intel/egg/reclass/datatypes/parameters.py", line 191, in _merge_recurse
  File "build/bdist.macosx-10.12-intel/egg/reclass/datatypes/parameters.py", line 163, in _merge_dict
  File "build/bdist.macosx-10.12-intel/egg/reclass/datatypes/parameters.py", line 191, in _merge_recurse
  File "build/bdist.macosx-10.12-intel/egg/reclass/datatypes/parameters.py", line 163, in _merge_dict
  File "build/bdist.macosx-10.12-intel/egg/reclass/datatypes/parameters.py", line 191, in _merge_recurse
  File "build/bdist.macosx-10.12-intel/egg/reclass/datatypes/parameters.py", line 163, in _merge_dict
  File "build/bdist.macosx-10.12-intel/egg/reclass/datatypes/parameters.py", line 191, in _merge_recurse
  File "build/bdist.macosx-10.12-intel/egg/reclass/datatypes/parameters.py", line 159, in _merge_dict
AttributeError: 'float' object has no attribute 'startswith'```

**Comment by Rtzq0** [comment]
Och, yeah unfair presumption on my part. I think that fix is probably a sane suggestion. YAML spec does not require keys to be strings, but in the case that they are not I'm not sure how we'd specify the override functionality.

Would you be willing to submit a PR for this or would you prefer that I do so?
