### ISSUE TITLE
Failed to install under Python 3.5.3

### ISSUE THREAD

**Issue by yujunz** [madduck/reclass#81]
Got an exception `ImportError: No module named 'output'`

See full logs below

```
➜  ~ python --version
Python 3.5.3
➜  ~ pip install reclass
Collecting reclass
  Using cached reclass-1.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/tf/g7vrf5ns5ql_bv82wz9t_0rr0000gn/T/pip-build-10z38jyf/reclass/setup.py", line 10, in <module>
        from reclass.version import *
      File "/private/var/folders/tf/g7vrf5ns5ql_bv82wz9t_0rr0000gn/T/pip-build-10z38jyf/reclass/reclass/__init__.py", line 10, in <module>
        from output import OutputLoader
    ImportError: No module named 'output'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/tf/g7vrf5ns5ql_bv82wz9t_0rr0000gn/T/pip-build-10z38jyf/reclass/
```

**Comment by ketzacoatl** [comment]
I see the same:

```
root@ubuntu-xenial:~# python --version
Python 3.5.2
```

```
root@ubuntu-xenial:~# pip3 install reclass
Collecting reclass
  Using cached https://files.pythonhosted.org/packages/e6/e2/7ab398b65da859966784f81145efa37d577005fc43432dd7b0f252196a98/reclass-1.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zo5cd8c6/reclass/setup.py", line 10, in <module>
        from reclass.version import *
      File "/tmp/pip-build-zo5cd8c6/reclass/reclass/__init__.py", line 10, in <module>
        from output import OutputLoader
    ImportError: No module named 'output'
```

**Comment by ketzacoatl** [comment]
I have made some updates to get python 3 to run `python setup.py install` without major error:

```
# python3 setup.py install
...
Processing reclass-1.4.1-py3.5.egg
Removing /usr/local/lib/python3.5/dist-packages/reclass-1.4.1-py3.5.egg
Copying reclass-1.4.1-py3.5.egg to /usr/local/lib/python3.5/dist-packages
reclass 1.4.1 is already the active version in easy-install.pth
Installing reclass-ansible script to /usr/local/bin
Installing reclass-salt script to /usr/local/bin
Installing reclass script to /usr/local/bin

Installed /usr/local/lib/python3.5/dist-packages/reclass-1.4.1-py3.5.egg
Processing dependencies for reclass==1.4.1
Searching for PyYAML==3.11
Best match: PyYAML 3.11
PyYAML 3.11 is already the active version in easy-install.pth

Using /usr/lib/python3/dist-packages
Finished processing dependencies for reclass==1.4.1
```
I have pushed a WIP branch with the changes - https://github.com/ketzacoatl/reclass/tree/py3-wip-update. More needs to be done to get this tested / functional with both python 2 and 3.
